### ISSUE TITLE
在blog中内嵌在线PPT

### ISSUE THREAD

**Issue by scuplus** [mohuishou/blogComment#1]
https://lailin.xyz/post/notes/%E5%9C%A8blog%E4%B8%AD%E5%86%85%E5%B5%8C%E5%9C%A8%E7%BA%BFppt/#gitalk-container 

 有时我们会做一些分享，分享之后可以把 PPT 脱敏之后放在博客上面，可以使用office online 直接内嵌 PPT。巨硬大法好

**Comment by mohuishou** [comment]
comment test `test`
