### ISSUE TITLE
About Me | mohuishou

### ISSUE THREAD

**Issue by scuplus** [mohuishou/blogComment#8]
https://lailin.xyz/about/ 

 mohuishou/scuplus/we川大

**Comment by AnnoraChan** [comment]
啊啊大佬有关于那个we川大那个微信小程序想模仿着做一个自己学校的遇到了点问题不知道能否帮忙解决一下呀QAQ

**Comment by mohuishou** [comment]
在scuplus-wechat这个仓库提issues就行

**Comment by mohuishou** [comment]
> @AnnoraChan
> 啊啊大佬有关于那个we川大那个微信小程序想模仿着做一个自己学校的遇到了点问题不知道能否帮忙解决一下呀QAQ

你直接在 scuplus-wechat这个仓库提交issue就行

**Comment by AnnoraChan** [comment]
后端代码感觉不是特别明白运行好像也有点问题希望大佬能帮忙解答一下不知道大佬有没有qq微信或者邮箱啥的orz

**Comment by mohuishou** [comment]
> @AnnoraChan
> 后端代码感觉不是特别明白运行好像也有点问题希望大佬能帮忙解答一下不知道大佬有没有qq微信或者邮箱啥的orz

github.com/mohuishou 在这里可以看到我的邮箱，不过最好还是提交issue，后端的提交到后端的仓库就好

**Comment by Yida147** [comment]
哈哈哈哈，看到你16年nginx排错的日志了，我最近也遇到了，没想到在你这儿找到了答案~棒👍

**Comment by scuplus** [comment]
> @Yida147
> 哈哈哈哈，看到你16年nginx排错的日志了，我最近也遇到了，没想到在你这儿找到了答案~棒👍

都是坑
